#!/usr/bin/env bash

# Setup build environment for service
#
# THIS FILE IS GENERATED BY THE COMPOSER AND USED BY THE PIPELINE - MODIFICATION WILL BE OVERWRITTEN
#
# Usage:
#   source env.sh [build|local] [PATH] [--skip-vault]
#
# Arguments:
#   build|local   Development environment mode (default: build)
#                 - build: Uses env-build.sh for build configuration
#                 - local: Uses env-local.sh for local development runtime configuration
#   PATH          Path to directory containing catalog-info.yaml (default: current directory)
#   --skip-vault  Skip Vault authentication (for CI/CD or offline builds)
#
# Examples:
#   source env.sh                          # Load from current dir, build mode
#   source env.sh local                    # Load from current dir, local mode
#   source env.sh build ./backend          # Load from ./backend, build mode
#   source env.sh build --skip-vault       # Load from current dir, skip Vault
#
# This script:
#   1. Validates that the PATH catalog file is a component (kind: Component)
#   2. Authenticates with Knox Vault (unless --skip-vault specified)
#   3. Sources PATH/.env-build.sh (always), and optionally PATH/.env-local.sh (if local mode)
#
# Environment variables set:
#   VAULT_ADDR    Knox Vault address
#   VAULT_TOKEN   Authentication token (if not --skip-vault)
#   Plus any additional variables from PATH/.env-build.sh and PATH/.env-local.sh

# Parse parameters
ENV_MODE="build"  # Default to build mode
TARGET_PATH="."
SKIP_VAULT=false

# Check first parameter for mode
if [[ "${1:-}" == "local" || "${1:-}" == "build" ]]; then
  ENV_MODE="${1}"
  shift
fi

# Check remaining parameters for path and flags
while [[ $# -gt 0 ]]; do
  case "${1}" in
    --skip-vault)
      SKIP_VAULT=true
      shift
      ;;
    *)
      TARGET_PATH="${1}"
      shift
      ;;
  esac
done

# Default path if not provided
TARGET_PATH="${TARGET_PATH:-.}"

# Check if catalog-info.yaml exists
CATALOG_FILE="${TARGET_PATH}/catalog-info.yaml"
if [[ ! -f "$CATALOG_FILE" ]]; then
  echo "Error: catalog-info.yaml not found at ${TARGET_PATH}" >&2
  return 1 2>/dev/null || exit 1
fi

# Check if kind is Component
KIND=$(grep "^kind:" "$CATALOG_FILE" | head -1 | sed 's/\w*kind: *//; s/ *#.*//')
if [[ "$KIND" != "Component" ]]; then
  echo "Error: catalog-info.yaml kind is '${KIND}', expected 'Component'" >&2
  return 1 2>/dev/null || exit 1
fi

export VAULT_ADDR="https://knox.io.nrs.gov.bc.ca"
# Check if VAULT_TOKEN is already valid, otherwise login (unless --skip-vault)
if [[ "$SKIP_VAULT" == false ]]; then
  if [[ -z "${VAULT_TOKEN:-}" ]] || ! vault token lookup &>/dev/null 2>&1; then
    export VAULT_TOKEN=$(vault login -method=oidc -format json 2>/dev/null | jq -r '.auth.client_token')
  fi
fi

# Source environment files from target path
# Always source env-build.sh first (contains service config and credentials)
ENV_build_FILE="${TARGET_PATH}/.env-build.sh"
if [[ -f "$ENV_build_FILE" ]]; then
  if [[ "$SKIP_VAULT" == true ]]; then
    source "$ENV_build_FILE" --skip-vault
  else
    source "$ENV_build_FILE"
  fi
fi

# If local mode, also source env-local.sh for additional development settings
if [[ "$ENV_MODE" == "local" ]]; then
  ENV_LOCAL_FILE="${TARGET_PATH}/.env-local.sh"
  if [[ -f "$ENV_LOCAL_FILE" ]]; then
    if [[ "$SKIP_VAULT" == true ]]; then
      source "$ENV_LOCAL_FILE" --skip-vault
    else
      source "$ENV_LOCAL_FILE"
    fi
  fi
fi
