#!/usr/bin/env bash

# Service-specific environment configuration
#
# THIS FILE IS GENERATED BY THE COMPOSER AND USED BY THE PIPELINE - MODIFICATION WILL BE OVERWRITTEN
#
# NOTE: This file should not be sourced directly. It is automatically sourced by env.sh
#       after validating the catalog-info.yaml and setting up Vault authentication.
#       Use: source env.sh [PATH] [--skip-vault] instead
#

# Check for --skip-vault flag
SKIP_VAULT=false
if [[ "${1:-}" == "--skip-vault" ]]; then
  SKIP_VAULT=true
fi

# Service-specific environment variables
export PROJECT_NAME="qs-knox"
export SERVICE_NAME="qs-knox-backend"
export PACKAGE_REPO="https://maven.pkg.github.com/bcgov/oscar-qs-knox"

# Non-Maven build configuration (e.g. Node)
DEFAULT_VERSION="$(jq -r '.version // empty' "$(dirname "${BASH_SOURCE[0]}")/package.json" 2>/dev/null)"
export VERSION="${VERSION:-${DEFAULT_VERSION:-0.0.0}}"
